server:
  port: 2333
  address: 0.0.0.0

lavalink:
  server:
    password: "jarvisbot"
    sources:
      youtube: false
      soundcloud: true
      http: true
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    youtubePlaylistLoadLimit: 6
    playerUpdateInterval: 5
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: true
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.18.1"
      repository: "https://maven.lavalink.dev/releases"
      snapshot: false

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    clients:
      - MUSIC
      - WEB
      - ANDROID_VR
      - TVHTML5_SIMPLY
    oauth:
      enabled: true
      skipInitialization: false
      
logging:
  level:
    root: INFO
    lavalink: DEBUG
    dev.lavalink.youtube: DEBUG
    dev.lavalink.youtube.http.YoutubeOauth2Handler: DEBUG
    
# server:
#   port: 2333
#   address: 0.0.0.0
# lavalink:
#   server:
#     password: "jarvisbot"
#     sources:
#       youtube: false
#       soundcloud: true
#       http: true
# plugins:
#   youtube:
#     enabled: true
#     allowSearch: true
#     clients:
#       - ANDROID_VR
#       - TVHTML5_SIMPLY
#       - IOS
#     oauth:
#       enabled: false
# logging:
#   level:
#     root: INFO
#     lavalink: INFO
